/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.java.Login;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import javax.imageio.ImageIO;
import javax.swing.*;

import Main.java.Data.City;
import Main.java.Roles.*;
import Userinterface.java.Businessmen.BusinessmanDashboard;
import Userinterface.java.Businessmen.Smart_Industries;
import Userinterface.java.BusinessmenAdminWorkArea.BusinessmenAdminLeftPanel;
import Userinterface.java.Student.StudentDashboard;
import Userinterface.java.StudentAdminWorkArea.StudentAdminLeftPanel;
import Userinterface.java.SystemAdminWorkArea.SystemAdminLeftArea;
import Userinterface.java.Tourist.TouristDashboard;
import Userinterface.java.TouristAdminWorkArea.TouristAdminLeftPanel;
import com.db4o.ObjectSet;
import Main.java.Database.Database;
/**
 *
 * @author sukhadapradhan
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkArea
     */
    private JPanel Container;
    public Login(JPanel Container) {
        initComponents();
        this.Container = Container;
        ObjectSet<City> cities = Database.db.get(City.class);
        cityField.addItem("");
        while (cities.hasNext())
        {
            cityField.addItem(cities.next().getName());
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        LoginButton = new GUIComponents.RoundedPanel();
        LoginButton1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        cityField = new javax.swing.JComboBox<>();
        password = new javax.swing.JTextField();
        BufferedImage iconImg = null;
        try
        {
            iconImg = ImageIO.read(new File("logo_light.png"));
        }
        catch(Exception e)
        {
            System.out.println();
        }
        ImageIcon icn = new ImageIcon(iconImg.getScaledInstance(250, 200, Image.SCALE_DEFAULT));
        jLabel3 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        signUpRedirect = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(191, 227, 235));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(216, 238, 237));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 190, 218));
        jLabel2.setText("User Login");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 130, 50));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("User Name");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        LoginButton.setBackground(new java.awt.Color(51, 204, 255));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });

        LoginButton1.setBackground(new java.awt.Color(0, 0, 0));
        LoginButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        LoginButton1.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton1.setText("Login");
        LoginButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginButtonLayout = new javax.swing.GroupLayout(LoginButton);
        LoginButton.setLayout(LoginButtonLayout);
        LoginButtonLayout.setHorizontalGroup(
            LoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginButtonLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(LoginButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        LoginButtonLayout.setVerticalGroup(
            LoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginButtonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LoginButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 140, 50));

        username.setForeground(new java.awt.Color(237, 176, 98));
        username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 250, 30));

        add(cityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 250, 30));

        password.setForeground(new java.awt.Color(237, 176, 98));
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 250, 30));

        jLabel3.setIcon(icn);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 220, 170));

        error.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 51));
        add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        signUpRedirect.setForeground(new java.awt.Color(51, 102, 255));
        signUpRedirect.setText("Become a Member. SignUp");
        signUpRedirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpRedirectMouseClicked(evt);
            }
        });
        add(signUpRedirect, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 170, 20));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("City");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Password");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/sukhadapradhan/Smart City Full Project/Login Image Countless1.png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 628));
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void LoginButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButton1MouseClicked
        String user = username.getText();
        String pass = password.getText();

        if(user.isEmpty() || pass.isEmpty())
        {
            error.setText("Fields are empty");
            return;
        }
        User s = new User(user,null,pass);
        ObjectSet<User> result = Database.db.get(s);
        if(result.isEmpty())
        {
            error.setText("Username or password incorrect");
            return;
        }
        int city = cityField.getSelectedIndex();
        if(city<0)
        {
            error.setText("City not selected");
            return;
        }
        if(cityField.getItemAt(city).isEmpty())
        {
            error.setText("City not selected");
            return;
        }
        Database.city = cityField.getItemAt(city);
        System.out.println(Database.city);
        try
        {
            User found=result.next();
            Database.loggedIn =found;
            if(found instanceof Student)
            {
                StudentDashboard workarea = new StudentDashboard(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if(found instanceof Tourist)
            {
                TouristDashboard workarea = new TouristDashboard(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if(found instanceof Businessman)
            {
                BusinessmanDashboard workarea = new BusinessmanDashboard(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if (found instanceof MainAdmin)
            {
                SystemAdminLeftArea workarea = new SystemAdminLeftArea(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if (found instanceof StudentAdmin)
            {
                StudentAdminLeftPanel workarea = new StudentAdminLeftPanel(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if (found instanceof TouristAdmin)
            {
                TouristAdminLeftPanel workarea = new TouristAdminLeftPanel(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if (found instanceof BusinessAdmin)
            {
                BusinessmenAdminLeftPanel workarea = new BusinessmenAdminLeftPanel(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
        }
        catch(Exception e)
        {
            System.out.println();
        }
        
    }//GEN-LAST:event_LoginButton1MouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        String user = username.getText();
        String pass = password.getText();

        if(user.isEmpty() || pass.isEmpty())
        {
            error.setText("Fields are empty");
            return;
        }
        User s = new User(user,null,pass);
        ObjectSet<User> result = Database.db.get(s);
        int city = cityField.getSelectedIndex();
        if(city<0)
        {
            error.setText("City not selected");
            return;
        }
        if(cityField.getItemAt(city).isEmpty())
        {
            error.setText("City not selected");
            return;
        }
        if(result.isEmpty())
        {
            error.setText("Username or password incorrect");
            return;
        }
        try
        {
            User found=result.next();
            Database.loggedIn =found;
            Database.city = cityField.getItemAt(city);
            if(found instanceof Student)
            {
                StudentDashboard workarea = new StudentDashboard(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if(found instanceof Tourist)
            {
                TouristDashboard workarea = new TouristDashboard(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if(found instanceof Businessman)
            {
                BusinessmanDashboard workarea = new BusinessmanDashboard(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if (found instanceof MainAdmin)
            {
                SystemAdminLeftArea workarea = new SystemAdminLeftArea(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if (found instanceof StudentAdmin)
            {
                StudentAdminLeftPanel workarea = new StudentAdminLeftPanel(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if (found instanceof TouristAdmin)
            {
                TouristAdminLeftPanel workarea = new TouristAdminLeftPanel(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
            else if (found instanceof BusinessAdmin)
            {
                BusinessmenAdminLeftPanel workarea = new BusinessmenAdminLeftPanel(Container);
                Container.add(workarea);
                CardLayout layout = (CardLayout) Container.getLayout();
                layout.next(Container);
                workarea.setVisible(true);
            }
        }
        catch(Exception e)
        {
            System.out.println();
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void signUpRedirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpRedirectMouseClicked
        Signup workarea = new Signup(Container);
        Container.add(workarea);
        CardLayout layout = (CardLayout) Container.getLayout();
        layout.next(Container);
    }//GEN-LAST:event_signUpRedirectMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIComponents.RoundedPanel LoginButton;
    private javax.swing.JLabel LoginButton1;
    private javax.swing.JComboBox<String> cityField;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField password;
    private javax.swing.JLabel signUpRedirect;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
