/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.java.SystemAdminWorkArea;

import Main.java.Data.City;
import Main.java.Database.Database;
import com.db4o.ObjectSet;

import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

/**
 *
 * @author sukhadapradhan
 */
public class ManageNetworks extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkArea
     */
    public ManageNetworks() {
        initComponents();
        ObjectSet<City> cities = Database.db.get(City.class);
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        for(City c :cities){
            model.addRow(new Object[]{c.getName()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cityName = new javax.swing.JTextField();
        CreateButton = new GUIComponents.RoundedPanel();
        CreateButton1 = new javax.swing.JLabel();
        deleteButton = new GUIComponents.RoundedPanel();
        deleteButton1 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(722, 677));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(722, 677));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Manage Networks");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 210, 40));

        jTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable.setForeground(new java.awt.Color(51, 51, 255));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setFocusable(false);
        jTable.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jScrollPane2.setViewportView(jTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 450, 190));

        jLabel3.setText("Enter City Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        cityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityNameActionPerformed(evt);
            }
        });
        jPanel2.add(cityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 210, 40));

        CreateButton.setBackground(new java.awt.Color(51, 204, 255));
        CreateButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateButton.setToolTipText("");
        CreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateButtonMouseClicked(evt);
            }
        });

        CreateButton1.setBackground(new java.awt.Color(0, 0, 0));
        CreateButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        CreateButton1.setForeground(new java.awt.Color(255, 255, 255));
        CreateButton1.setText("Create");
        CreateButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CreateButtonLayout = new javax.swing.GroupLayout(CreateButton);
        CreateButton.setLayout(CreateButtonLayout);
        CreateButtonLayout.setHorizontalGroup(
            CreateButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateButtonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(CreateButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        CreateButtonLayout.setVerticalGroup(
            CreateButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateButtonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CreateButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(CreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 140, 50));

        deleteButton.setBackground(new java.awt.Color(51, 204, 255));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setToolTipText("");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        deleteButton1.setBackground(new java.awt.Color(0, 0, 0));
        deleteButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        deleteButton1.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton1.setText("Delete");
        deleteButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout deleteButtonLayout = new javax.swing.GroupLayout(deleteButton);
        deleteButton.setLayout(deleteButtonLayout);
        deleteButtonLayout.setHorizontalGroup(
            deleteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteButtonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(deleteButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        deleteButtonLayout.setVerticalGroup(
            deleteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteButtonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deleteButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, 50));

        error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 220, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityNameActionPerformed

    private void CreateButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateButton1MouseClicked

        String city = cityName.getText();
        city = city.toUpperCase();
        City c = new City(city);
        ObjectSet<City> cities = Database.db.get(c);
        if(!cities.isEmpty())
        {
            error.setText("Field is empty");
            return;
        }
        else
        {
            Database.db.set(c);
            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
            model.addRow(new Object[]{c.getName()});
        }
        cityName.setText("");


    }//GEN-LAST:event_CreateButton1MouseClicked

    private void CreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateButtonMouseClicked
        String city = cityName.getText();
        city = city.toUpperCase();
        City c = new City(city);
        ObjectSet<City> cities = Database.db.get(c);
        if(!cities.isEmpty())
        {
            error.setText("Field is empty");
            return;
        }
        else
        {

            Database.db.set(c);
            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
            model.addRow(new Object[]{c.getName()});
        }
        cityName.setText("");
    }//GEN-LAST:event_CreateButtonMouseClicked

    private void deleteButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButton1MouseClicked
        int row = jTable.getSelectedRow();
        int column = jTable.getSelectedColumn();
        String city= (String)jTable.getValueAt(row,column);
        City c  = new City(city);
        ObjectSet<City> result= Database.db.get(c);
        if(result.hasNext())
        {
            c = result.next();
            Database.db.delete(c);
        }
        ((DefaultTableModel)jTable.getModel()).removeRow(row);
        
    }//GEN-LAST:event_deleteButton1MouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
        int row = jTable.getSelectedRow();
        int column = jTable.getSelectedColumn();
        String city= (String)jTable.getValueAt(row,column);
        City c  = new City(city);
        ObjectSet<City> result= Database.db.get(c);
        if(result.hasNext())
        {
            c = result.next();
            Database.db.delete(c);
        }
        ((DefaultTableModel)jTable.getModel()).removeRow(row);
    }//GEN-LAST:event_deleteButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIComponents.RoundedPanel CreateButton;
    private javax.swing.JLabel CreateButton1;
    private javax.swing.JTextField cityName;
    private GUIComponents.RoundedPanel deleteButton;
    private javax.swing.JLabel deleteButton1;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
