/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.java.SystemAdminWorkArea;

import Main.java.Database.Database;
import Main.java.Roles.BusinessAdmin;
import Main.java.Roles.User;
import com.db4o.ObjectSet;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sukhadapradhan
 */
public class ManageBusinessmenAdmin extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkArea
     */
    public ManageBusinessmenAdmin() {
        initComponents();
        ObjectSet<BusinessAdmin> businessAdmins = Database.db.get(BusinessAdmin.class);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(BusinessAdmin c :businessAdmins){
            model.addRow(new Object[]{c.getEmail(),c.getUsername(),c.getPassword()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        UserNameTxtFld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PasswordTxtFld = new javax.swing.JTextField();
        createButton = new GUIComponents.RoundedPanel();
        createButton1 = new javax.swing.JLabel();
        editButton = new GUIComponents.RoundedPanel();
        editButton1 = new javax.swing.JLabel();
        deleteButton = new GUIComponents.RoundedPanel();
        deleteButton1 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Manage Businessmen Admin");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 340, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "UserID", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 140, 510, 170));

        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Email");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 50, -1));

        emailField.setForeground(new java.awt.Color(0, 102, 204));
        emailField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 204)));
        jPanel2.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 190, -1));

        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("UserName");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, 20));

        UserNameTxtFld.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 204)));
        jPanel2.add(UserNameTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 190, 20));

        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        PasswordTxtFld.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 204)));
        jPanel2.add(PasswordTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 190, -1));

        createButton.setBackground(new java.awt.Color(51, 204, 255));
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });

        createButton1.setBackground(new java.awt.Color(0, 0, 0));
        createButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        createButton1.setForeground(new java.awt.Color(255, 255, 255));
        createButton1.setText("Create");
        createButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout createButtonLayout = new javax.swing.GroupLayout(createButton);
        createButton.setLayout(createButtonLayout);
        createButtonLayout.setHorizontalGroup(
            createButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createButtonLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(createButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        createButtonLayout.setVerticalGroup(
            createButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createButtonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(createButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 140, 50));

        editButton.setBackground(new java.awt.Color(51, 204, 255));
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });

        editButton1.setBackground(new java.awt.Color(0, 0, 0));
        editButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        editButton1.setForeground(new java.awt.Color(255, 255, 255));
        editButton1.setText("Edit");
        editButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editButtonLayout = new javax.swing.GroupLayout(editButton);
        editButton.setLayout(editButtonLayout);
        editButtonLayout.setHorizontalGroup(
            editButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editButtonLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(editButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        editButtonLayout.setVerticalGroup(
            editButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editButtonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(editButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, 50));

        deleteButton.setBackground(new java.awt.Color(51, 204, 255));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        deleteButton1.setBackground(new java.awt.Color(0, 0, 0));
        deleteButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        deleteButton1.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton1.setText("Delete");
        deleteButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout deleteButtonLayout = new javax.swing.GroupLayout(deleteButton);
        deleteButton.setLayout(deleteButtonLayout);
        deleteButtonLayout.setHorizontalGroup(
            deleteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteButtonLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(deleteButton1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        deleteButtonLayout.setVerticalGroup(
            deleteButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteButtonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deleteButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, 50));

        error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1902, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButton1MouseClicked
        String use = UserNameTxtFld.getText();
        String em = emailField.getText();
        String p1 = PasswordTxtFld.getText();
        if(use.isEmpty() || em.isEmpty() || p1.isEmpty())
        {
            error.setText("Fields are empty");
            return;
        }
        User u = new User(use,null,null);
        ObjectSet<User> users = Database.db.get(u);
        if(!users.isEmpty())
        {
            error.setText("Username already in use");
            return;
        }
        u = new User(null,em,null);
        users = Database.db.get(u);
        if(!users.isEmpty())
        {
            error.setText("Email already in use");
            return;
        }
        BusinessAdmin sa= new BusinessAdmin(use,em,p1);
        Database.db.set(sa);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{sa.getEmail(),sa.getUsername(),sa.getPassword()});
        UserNameTxtFld.setText("");
        emailField.setText("");
        PasswordTxtFld.setText("");
    }//GEN-LAST:event_createButton1MouseClicked

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        String use = UserNameTxtFld.getText();
        String em = emailField.getText();
        String p1 = PasswordTxtFld.getText();
        if(use.isEmpty() || em.isEmpty() || p1.isEmpty())
        {
            error.setText("Fields are empty");
            return;
        }
        User u = new User(use,null,null);
        ObjectSet<User> users = Database.db.get(u);
        if(!users.isEmpty())
        {
            error.setText("Username already in use");
            return;
        }
        u = new User(null,em,null);
        users = Database.db.get(u);
        if(!users.isEmpty())
        {
            error.setText("Email already in use");
            return;
        }
        BusinessAdmin sa= new BusinessAdmin(use,em,p1);
        Database.db.set(sa);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{sa.getEmail(),sa.getUsername(),sa.getPassword()});
        UserNameTxtFld.setText("");
        emailField.setText("");
        PasswordTxtFld.setText("");
    }//GEN-LAST:event_createButtonMouseClicked

    private void editButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButton1MouseClicked
        int row = jTable1.getSelectedRow();
        String use = UserNameTxtFld.getText();
        String email = emailField.getText();
        String p1 = PasswordTxtFld.getText();
        if(use.isEmpty() || email.isEmpty() || p1.isEmpty())
        {
            
            return;
        }
        if(row<0)
        {
            error.setText("Select a Row");
            return;
        }
        int column = 0;
        String em= (String)jTable1.getValueAt(row,column);
        BusinessAdmin c  = new BusinessAdmin(null,em,null);
        ObjectSet<BusinessAdmin> result= Database.db.get(c);
        if(result.hasNext())
        {
            c = result.next();
            c.setEmail(emailField.getText());
            c.setUsername(UserNameTxtFld.getText());
            c.setPassword(PasswordTxtFld.getText());
            Database.db.store(c);
            ((DefaultTableModel)jTable1.getModel()).setValueAt(c.getEmail(),row,0);
            ((DefaultTableModel)jTable1.getModel()).setValueAt(c.getUsername(),row,1);
            ((DefaultTableModel)jTable1.getModel()).setValueAt(c.getPassword(),row,2);
            UserNameTxtFld.setText("");
            emailField.setText("");
            PasswordTxtFld.setText("");
            error.setText("");
        }

    }//GEN-LAST:event_editButton1MouseClicked

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        int row = jTable1.getSelectedRow();
        String use = UserNameTxtFld.getText();
        String email = emailField.getText();
        String p1 = PasswordTxtFld.getText();
        if(use.isEmpty() || email.isEmpty() || p1.isEmpty())
        {
            
            return;
        }
        if(row<0)
        {
            error.setText("Select a Row");
            return;
        }
        int column = 0;
        String em= (String)jTable1.getValueAt(row,column);
        BusinessAdmin c  = new BusinessAdmin(null,em,null);
        ObjectSet<BusinessAdmin> result= Database.db.get(c);
        if(result.hasNext())
        {
            c = result.next();
            c.setEmail(emailField.getText());
            c.setUsername(UserNameTxtFld.getText());
            c.setPassword(PasswordTxtFld.getText());
            Database.db.store(c);
            ((DefaultTableModel)jTable1.getModel()).setValueAt(c.getEmail(),row,0);
            ((DefaultTableModel)jTable1.getModel()).setValueAt(c.getUsername(),row,1);
            ((DefaultTableModel)jTable1.getModel()).setValueAt(c.getPassword(),row,2);
            UserNameTxtFld.setText("");
            emailField.setText("");
            PasswordTxtFld.setText("");
            error.setText("");
        }
    }//GEN-LAST:event_editButtonMouseClicked

    private void deleteButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButton1MouseClicked
        int row = jTable1.getSelectedRow();
        int column = 0;
        String em= (String)jTable1.getValueAt(row,column);
        BusinessAdmin c  = new BusinessAdmin(null,em,null);
        ObjectSet<BusinessAdmin> result= Database.db.get(c);
        if(result.hasNext())
        {
            c = result.next();
            Database.db.delete(c);
        }
        ((DefaultTableModel)jTable1.getModel()).removeRow(row);
        UserNameTxtFld.setText("");
        emailField.setText("");
        PasswordTxtFld.setText("");
    }//GEN-LAST:event_deleteButton1MouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        int row = jTable1.getSelectedRow();
        int column = 0;
        String em= (String)jTable1.getValueAt(row,column);
        BusinessAdmin c  = new BusinessAdmin(null,em,null);
        ObjectSet<BusinessAdmin> result= Database.db.get(c);
        if(result.hasNext())
        {
            c = result.next();
            Database.db.delete(c);
        }
        ((DefaultTableModel)jTable1.getModel()).removeRow(row);
        UserNameTxtFld.setText("");
        emailField.setText("");
        PasswordTxtFld.setText("");
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();
        if(row>=0)
        {
            emailField.setText(jTable1.getValueAt(row,0).toString());
            UserNameTxtFld.setText(jTable1.getValueAt(row,1).toString());
            PasswordTxtFld.setText(jTable1.getValueAt(row,2).toString());
        }
        else
        {
            emailField.setText("");
            UserNameTxtFld.setText("");
            PasswordTxtFld.setText("");
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PasswordTxtFld;
    private javax.swing.JTextField UserNameTxtFld;
    private GUIComponents.RoundedPanel createButton;
    private javax.swing.JLabel createButton1;
    private GUIComponents.RoundedPanel deleteButton;
    private javax.swing.JLabel deleteButton1;
    private GUIComponents.RoundedPanel editButton;
    private javax.swing.JLabel editButton1;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
