/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main.java.Homepage;

import Main.java.Data.Job;
import Main.java.Database.Database;
import Main.java.Login.Login;
import Main.java.Login.Signup;
import Main.java.Roles.MainAdmin;
import Main.java.Roles.Student;
import Main.java.Roles.User;
import com.db4o.ObjectSet;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author sukhadapradhan
 */
public class Homepage extends javax.swing.JPanel {
      
    /**
     * Creates new form SystemAdminWorkArea
     */
    private JPanel Container;
    public Homepage(JPanel Container) {
        initComponents();
        this.Container = Container;
        Student s = new Student(null,"sukhadapradhan@gmail.com",null);
        ObjectSet<Student> student = Database.db.get(s);
        if(!student.isEmpty()){
               s=student.next();
              System.out.println(s.getUsername()+ " "+ s.getEmail()+" " +s.getPassword());
        }

//        MainAdmin s = new MainAdmin("sysadmin","admin@gmail.com","sysadmin");
//        Database.db.set(s);
//        User c  = new User(null,"shoaibmoeen4343@gmail.com",null);
//        ObjectSet<User> result= Database.db.get(c);
//       c = result.next();
//       Database.db.delete(c);
    }

    public Homepage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BufferedImage iconImg = null;
        try
        {
            iconImg = ImageIO.read(new File("logo_light.png"));
        }
        catch(Exception e)
        {
            System.out.println();
        }
        ImageIcon icn = new ImageIcon(iconImg.getScaledInstance(250, 200, Image.SCALE_DEFAULT));
        jLabel3 = new javax.swing.JLabel();
        LoginButton = new GUIComponents.RoundedPanel();
        LoginButton1 = new javax.swing.JLabel();
        RegisterButton = new GUIComponents.RoundedPanel();
        RegisterButtontext = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(191, 227, 235));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(icn);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 220, 170));

        LoginButton.setBackground(new java.awt.Color(51, 204, 255));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });

        LoginButton1.setBackground(new java.awt.Color(0, 0, 0));
        LoginButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        LoginButton1.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton1.setText("Login");
        LoginButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginButtonLayout = new javax.swing.GroupLayout(LoginButton);
        LoginButton.setLayout(LoginButtonLayout);
        LoginButtonLayout.setHorizontalGroup(
            LoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginButtonLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(LoginButton1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        LoginButtonLayout.setVerticalGroup(
            LoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginButtonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LoginButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 140, 50));

        RegisterButton.setBackground(new java.awt.Color(51, 204, 255));
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });

        RegisterButtontext.setBackground(new java.awt.Color(0, 0, 0));
        RegisterButtontext.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        RegisterButtontext.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButtontext.setText("Register");
        RegisterButtontext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtontextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RegisterButtonLayout = new javax.swing.GroupLayout(RegisterButton);
        RegisterButton.setLayout(RegisterButtonLayout);
        RegisterButtonLayout.setHorizontalGroup(
            RegisterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterButtonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(RegisterButtontext)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        RegisterButtonLayout.setVerticalGroup(
            RegisterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterButtonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(RegisterButtontext)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/sukhadapradhan/Smart City Full Project/Login Image Countless1.png")); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(300, 500));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 630));
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void RegisterButtontextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtontextMouseClicked
        // TODO add your handling code here:
        Signup workarea = new Signup(Container);
        Container.add(workarea);
        CardLayout layout = (CardLayout) Container.getLayout();
        layout.next(Container);
    }//GEN-LAST:event_RegisterButtontextMouseClicked

    private void LoginButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButton1MouseClicked
        Login workarea = new Login(Container);
        Container.add(workarea);
        CardLayout layout = (CardLayout) Container.getLayout();
        layout.next(Container);
    }//GEN-LAST:event_LoginButton1MouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked

        Login workarea = new Login(Container);
        Container.add(workarea);
        CardLayout layout = (CardLayout) Container.getLayout();
        layout.next(Container);
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
        // TODO add your handling code here:
        Signup workarea = new Signup(Container);
        Container.add(workarea);
        CardLayout layout = (CardLayout) Container.getLayout();
        layout.next(Container);
        workarea.setVisible(true);
    }//GEN-LAST:event_RegisterButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIComponents.RoundedPanel LoginButton;
    private javax.swing.JLabel LoginButton1;
    private GUIComponents.RoundedPanel RegisterButton;
    private javax.swing.JLabel RegisterButtontext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
