/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface.java.Tourist;

import Main.java.Database.Database;
import Main.java.Login.Login;
import Userinterface.java.Student.*;

import javax.swing.*;
import java.awt.Container.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
/**
 *
 * @author sukhadapradhan
 */
public class TouristDashboard extends javax.swing.JPanel {

    /**
     * Creates new form StudentDashboard
     */
    private JPanel container;
    public TouristDashboard(JPanel c) {
        initComponents();
        container=c;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        BufferedImage iconImg = null;
        try
        {
            iconImg = ImageIO.read(new File("main_logo.png"));
        }
        catch(Exception e)
        {
            System.out.println();
        }
        ImageIcon icn = new ImageIcon(iconImg.getScaledInstance(140, 112, Image.SCALE_DEFAULT));
        jLabel3 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        hotels = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        spots = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        parkings = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, 43));

        logout.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel3.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        home.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Smart City");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel3.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setIcon(icn);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -20, 120, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1950, 80));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Services Offered");

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hotels.setBackground(new java.awt.Color(0, 204, 255));
        hotels.setForeground(new java.awt.Color(255, 255, 255));
        hotels.setText("         Smart Hotels");
        hotels.setOpaque(true);
        hotels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hotelsMouseClicked(evt);
            }
        });
        jPanel5.add(hotels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 157, 28));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/sukhadapradhan/Smart City Full Project/icons8-hotel-80.png")); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 157, 120));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spots.setBackground(new java.awt.Color(0, 204, 255));
        spots.setForeground(new java.awt.Color(255, 255, 255));
        spots.setText("     Smart Tourist Spots");
        spots.setOpaque(true);
        spots.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spotsMouseClicked(evt);
            }
        });
        jPanel6.add(spots, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 158, 28));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/sukhadapradhan/Smart City Full Project/icons8-theme-park-80.png")); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 157, 120));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parkings.setBackground(new java.awt.Color(0, 204, 255));
        parkings.setForeground(new java.awt.Color(255, 255, 255));
        parkings.setText("        Smart Parking");
        parkings.setOpaque(true);
        parkings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parkingsMouseClicked(evt);
            }
        });
        jPanel7.add(parkings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 146, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/sukhadapradhan/Smart City Full Project/icons8-car-80.png")); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 146, 120));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 870, 490));

        MainPanel.add(jPanel8, "card2");

        jPanel1.add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 1950, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hotelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hotelsMouseClicked
        Smart_Hotels workarea = new Smart_Hotels();
        MainPanel.add(workarea);
        CardLayout layout = (CardLayout) MainPanel.getLayout();
        layout.next(MainPanel);
        workarea.setVisible(true);
    }//GEN-LAST:event_hotelsMouseClicked

    private void spotsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spotsMouseClicked
        Smart_TouristSpots workarea = new Smart_TouristSpots();
        MainPanel.add(workarea);
        CardLayout layout = (CardLayout) MainPanel.getLayout();
        layout.next(MainPanel);
        workarea.setVisible(true);
    }//GEN-LAST:event_spotsMouseClicked

    private void parkingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parkingsMouseClicked
        if(!Database.loggedIn.getParkingPermission())
        {
            Smart_Parking_1 workarea = new Smart_Parking_1();
            MainPanel.add(workarea);
            CardLayout layout = (CardLayout) MainPanel.getLayout();
            layout.next(MainPanel);
            workarea.setVisible(true);
        }
        else
        {
            Smart_Parking_2 workarea = new Smart_Parking_2(MainPanel);
            MainPanel.add(workarea);
            CardLayout layout = (CardLayout) MainPanel.getLayout();
            layout.next(MainPanel);
            workarea.setVisible(true);
        }
        
          
        
    }//GEN-LAST:event_parkingsMouseClicked
     
   
    
    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        
        MainPanel.add(jPanel8);
       
        CardLayout layout = (CardLayout) MainPanel.getLayout();
        layout.next(MainPanel);
        jPanel8.setVisible(true);
       
        
        
    }//GEN-LAST:event_homeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login workarea = new Login(container);
        container.add(workarea);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        workarea.setVisible(true); 
    }//GEN-LAST:event_logoutMouseClicked
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel home;
    private javax.swing.JLabel hotels;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel parkings;
    private javax.swing.JLabel spots;
    // End of variables declaration//GEN-END:variables
}
